#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin

set -e

[ -z "${VERBOSE}" ] || set -x -v

## remove aptitude and apt-utils (with many thanks)
apt -y purge aptitude apt-utils
apt -y autoremove
rm -rf /var/lib/aptitude

## remove apt cache and lists
for i in /var/lib/apt/lists /var/cache/apt/archives ; do
	[ -d "$i" ] || continue
	find $i/ -mindepth 1 -type f -delete
	install -o 0 -g 0 -m 0640 /dev/null $i/lock
done
apt-get clean

rm -rf \
  /var/lib/apt/lists/auxfiles \
  /var/cache/apt/pkgcache.bin \
  /var/cache/apt/srcpkgcache.bin
