#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin
set -f

[ -z "${VERBOSE}" ] || set -x -v

dpkg_cfg='/etc/dpkg/dpkg.cfg.d'
dpkg_info='/var/lib/dpkg/info'
shallow_cfg='/opt/cleanup.d/dpkg.cfg.d'
re_path='^path-((ex|in)clude=.+)$'

## first: cut away interesting rules from dpkg configuration
## to separate ("shallow") directory
tfiles=$(mktemp)
find "${dpkg_cfg}/" -maxdepth 1 -type f -exec grep -El "${re_path}" '{}' '+' > "${tfiles}"
if [ -s "${tfiles}" ] ; then
	t=$(mktemp)

	mkdir -p "${shallow_cfg}"

	while read -r conf ; do
		name=$(basename "${conf}")

		## save rules in separate file
		grep -E "${re_path}" < "${conf}" > "$t"

		## cut rules from original file
		## if it became empty - delete it
		sed -i -E "/(${re_path}|^\\s*\$)/d" "${conf}"
		grep -lqE '\S' "${conf}" || rm -f "${conf}"

		## reuse existing file if any
		[ -s "${shallow_cfg}/${name}" ] && cat "${shallow_cfg}/${name}" >> "$t"

		## remove trailing spaces, sort and remove duplicates
		sed -E 's/ +$//;' < "$t" \
		| sort -uV > "${shallow_cfg}/${name}"
	done < "${tfiles}"

	rm "$t" ; unset t
fi
rm -f "${tfiles}" ; unset tfiles

## nothing to filter at all
[ -d "${shallow_cfg}" ] || exit 0

## merge all rules and reformat them like "(ex|in)clude=/path/selector"
tpath=$(mktemp)
find "${shallow_cfg}/" -maxdepth 1 -type f -exec cat '{}' '+' \
| sed -En "/${re_path}/{s//\\1/;p;}" \
| sort -uV > "${tpath}"

## nothing to filter at all (again)
if ! [ -s "${tpath}" ] ; then
	rm -f "${tpath}"
	exit 0
fi

## reformat stanzas
sed -E -i 's/^exclude/delete/;s/^include/keep/;' "${tpath}"

## reformat dpkg's "globs" to "normal glob"
## TODO: discover more cases
sed -E -i 's#(^|/)\*($|/)#\1**\2#g;' "${tpath}"

## dry-run clean-glob-x.sh to get list of ready-to-delete files
tremove=$(mktemp)
PIPELINE=1 /opt/clean-glob-x.sh / "${tpath}" > "${tremove}"

## nothing to filter at all (again?!)
if ! [ -s "${tremove}" ] ; then
	rm -f "${tpath}" "${tremove}"
	exit 0
fi

## reuse temp file
tr '\0' '\n' < "${tremove}" > "${tpath}"

## list affected packages
taffected=$(mktemp)
find "${dpkg_info}/" -name '*.list' \
  -exec grep -Fxl -f "${tpath}" '{}' '+' \
| sed -E 's/^.*\/([^/]+)\.list$/\1/' \
| sort -uV > "${taffected}"

rm -f "${tpath}"

## remove files already!
xargs -0 -r rm -f < "${tremove}"

rm -f "${tremove}" ; unset tremove

## reconfigure affected packages
xargs -r dpkg-reconfigure --force < "${taffected}"
r=$?

rm -f "${taffected}" ; unset taffected

exit $r
