#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin

set -e -f

[ -z "${VERBOSE}" ] || set -x -v

## truncate files special files
## delete other files

/opt/xglob.sh /var/log <<-EOF
	delete=**
	keep=btmp
	keep=wtmp
	keep=faillog
	keep=lastlog
	keep=tallylog
EOF

find /var/log/ -xdev -type f -exec truncate -s 0 '{}' '+'
