#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin

set -e

[ -z "${VERBOSE}" ] || set -x -v

## truncate files special files
## delete other files
re='^/var/log/(btmp|wtmp|faillog|lastlog|tallylog)$'

find /var/log/ -xdev -regextype egrep \
  '(' -type f -regex "${re}" -exec truncate -s 0 '{}' '+' ')' \
  ',' \
  '(' -type f '!' -regex "${re}" -delete ')'
