#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin

set -e -f

[ -z "${VERBOSE}" ] || set -x -v

XGLOB_DIRS=1 /opt/xglob.sh / <<-EOF
	delete=**/*.pyc
	delete=**/__pycache__
EOF
