#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021, Konstantin Demin

set -e

[ -z "${VERBOSE}" ] || set -x -v

## topmost root
find / -maxdepth 1 -name '*.pyc' -type f -delete

## treewide
find / -mindepth 1 -maxdepth 1 -type d -print0 | \
grep -zEv '^/(sys|proc|dev)$' | \
sort -zV | \
xargs -0 -r -I'{}' \
  find '{}' -mindepth 1 -name '*.pyc' -type f -delete
